project:
  type: website
  output-dir: docs

website:
  title: "Noah Jansen"
  navbar:
    foreground: "#004225"
    highlight: "#56AE57"
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu: 
          - href: minip1.qmd
            text: Papers, Please!
          
            
          


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



